Analyte maps now plot with new data handling method
Updated DataHandling.py and main.py and anything else that was needed to up produce analyte maps again.  A lot will still be broken.  Also now working on updates to a custom TreeView class that makes interacting with the TreeView widgets a little easier.  Rearranged the filtering UI.

diff --git a/update_custom_widgets b/update_custom_widgets
--- a/update_custom_widgets
+++ b/update_custom_widgets
@@ -1,50 +1,50 @@
 #!/bin/bash
 
+# # Define the file to be updated
+# file="src/ui/MainWindow.py"
+
+# # update MainWindow.py
+# pyuic5 designer/mainwindow.ui -o $file
+
+# # Define the file containing the list of object names
+# object_names_file="src/widget_list_MainWindow.txt"
+
+# # Check if the files exist
+# if [[ ! -f "$file" ]]; then
+#   echo "File $file not found!"
+#   exit 1
+# fi
+
+# if [[ ! -f "$object_names_file" ]]; then
+#   echo "File $object_names_file not found!"
+#   exit 1
+# fi
+
+# # Add the import for CustomWidgets as cw if it doesn't exist
+# if ! grep -q "import src.CustomWidgets as cw" "$file"; then
+#   echo "Adding import for src.CustomWidgets as cw..."
+#   sed -i '' "1i\\
+# import src.CustomWidgets as cw
+# " "$file"
+# fi
+
+# # Replace 'QtWidgets.QLineEdit' with 'cw.CustomLineEdit' for specified object names
+# echo "Replacing 'QtWidgets.QLineEdit' with 'cw.CustomLineEdit' for specified object names..."
+# while IFS= read -r object_name; do
+#   sed -i '' "s/${object_name} = QtWidgets.QLineEdit/${object_name} = cw.CustomLineEdit/g" "$file"
+# done < "$object_names_file"
+
+# # Replace 'import resources_rc' with 'import src.ui.resources_rc'
+# echo "Replacing 'import resources_rc' with 'import src.ui.resources_rc'..."
+# sed -i '' "s/import resources_rc/import src.ui.resources_rc/g" "$file"
+
+# echo "Processing complete for $file"
+# echo
+
+
+
 # Define the file to be updated
-file="src/ui/MainWindow.py"
-
-# update MainWindow.py
-pyuic5 designer/mainwindow.ui -o $file
-
-# Define the file containing the list of object names
-object_names_file="src/widget_list_MainWindow.txt"
-
-# Check if the files exist
-if [[ ! -f "$file" ]]; then
-  echo "File $file not found!"
-  exit 1
-fi
-
-if [[ ! -f "$object_names_file" ]]; then
-  echo "File $object_names_file not found!"
-  exit 1
-fi
-
-# Add the import for CustomWidgets as cw if it doesn't exist
-if ! grep -q "import src.CustomWidgets as cw" "$file"; then
-  echo "Adding import for src.CustomWidgets as cw..."
-  sed -i '' "1i\\
-import src.CustomWidgets as cw
-" "$file"
-fi
-
-# Replace 'QtWidgets.QLineEdit' with 'cw.CustomLineEdit' for specified object names
-echo "Replacing 'QtWidgets.QLineEdit' with 'cw.CustomLineEdit' for specified object names..."
-while IFS= read -r object_name; do
-  sed -i '' "s/${object_name} = QtWidgets.QLineEdit/${object_name} = cw.CustomLineEdit/g" "$file"
-done < "$object_names_file"
-
-# Replace 'import resources_rc' with 'import src.ui.resources_rc'
-echo "Replacing 'import resources_rc' with 'import src.ui.resources_rc'..."
-sed -i '' "s/import resources_rc/import src.ui.resources_rc/g" "$file"
-
-echo "Processing complete for $file"
-echo
-
-
-
-# Define the file to be updated
-names=("FileSelectorDialog" "MapImportDialog")
+names=("MainWindow" "FileSelectorDialog" "MapImportDialog")
 
 # Function to determine widget type from object name
 get_widget_type() {
@@ -53,6 +53,7 @@ get_widget_type() {
   case "$object_name" in
     self.tableWidget*) echo "TableWidget" ;;
     self.lineEdit*) echo "LineEdit" ;;
+    self.treeView*) echo "TreeView" ;;
     # Add more patterns as needed
     *) echo "Unknown" ;;
   esac
@@ -62,8 +63,13 @@ get_widget_type() {
 for name in "${names[@]}"; do
   file="src/ui/$name.py"
 
-  # Generate the .py file from the .ui file using pyuic5
-  pyuic5 -x designer/$name.ui -o $file
+  if [ "$name" = "mainwindow" ]; then
+    # update MainWindow.py
+    pyuic5 designer/mainwindow.ui -o $file
+  else
+    # Generate the .py file from the .ui file using pyuic5
+    pyuic5 -x designer/$name.ui -o $file
+  fi
 
   # Define the file containing the list of object names
   object_names_file="src/widget_list_$name.txt"
@@ -96,6 +102,12 @@ import src.CustomWidgets as cw
     echo "    object name: $object_name, widget type: $widget_type"
     sed -i '' "s/${object_name} = QtWidgets.Q${widget_type}/${object_name} = cw.Custom${widget_type}/g" "$file"
   done < "$object_names_file"
+
+  if [ "$name" = "mainwindow" ]; then
+    # Replace 'import resources_rc' with 'import src.ui.resources_rc'
+    echo "Replacing 'import resources_rc' with 'import src.ui.resources_rc'..."
+    sed -i '' "s/import resources_rc/import src.ui.resources_rc/g" "$file"
+  fi
 
   echo "Processing completed for $name."
   echo
